name: Build Native Offline APK
on:
  workflow_dispatch:
    inputs:
      git_repo:
        description: 'Your Lovable GitHub URL'
        required: true
        # No default value
      app_name:
        description: 'App Name'
        required: true
        # No default value
      resumeUrl:
        description: 'Resume URL for n8n'
        required: false
        type: string

jobs:
  build:
    name: Build Native APK
    runs-on: ubuntu-latest
    steps:
      - name: Setup Runner
        uses: actions/checkout@v4

      - name: Setup Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # JDK 17 is generally more stable for Capacitor builds than 21
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone Repository
        run: |
          git clone ${{ inputs.git_repo }} source_code

      - name: Install Dependencies
        working-directory: ./source_code
        run: npm install

      - name: Build Web Assets (Vite)
        working-directory: ./source_code
        run: npm run build

      - name: ☢️ NUKE OLD CONFIG & FORCE LOCAL ☢️
        working-directory: ./source_code
        run: |
          # 1. DELETE existing config
          rm -f capacitor.config.ts capacitor.config.json
          
          # 2. Install Capacitor packages if missing
          npm install @capacitor/core @capacitor/cli @capacitor/android

          # 3. Generate Clean Package ID (Alphanumeric only, lowercase)
          PACKAGE_ID=$(echo "${{ inputs.app_name }}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]')
          
          # Initialize Capacitor
          npx cap init "${{ inputs.app_name }}" "com.lovable.${PACKAGE_ID}" --web-dir=dist

          # 4. Check dist existence
          if [ ! -d "dist" ]; then
            echo "ERROR: 'dist' folder missing. Build failed."
            exit 1
          fi

      - name: Create Android Project
        working-directory: ./source_code
        run: |
          npx cap add android
          npx cap sync android

      - name: Build APK (Gradle)
        working-directory: ./source_code/android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-offline
          path: source_code/android/app/build/outputs/apk/debug/app-debug.apk

      # Upload to Catbox so n8n can access the file
      - name: Upload APK Publicly
        id: upload_file
        run: |
          APK_PATH=$(find . -name "app-debug.apk" | head -n 1)
          
          if [ -z "$APK_PATH" ]; then
            echo "::error::APK file not found!"
            exit 1
          fi

          echo "Found APK at: $APK_PATH"
          
          # Upload to Catbox
          LINK=$(curl -F "reqtype=fileupload" -F "fileToUpload=@$APK_PATH" https://catbox.moe/user/api.php)
          
          echo "Public Link: $LINK"
          echo "apk_url=$LINK" >> $GITHUB_OUTPUT

      # Final signal to n8n that the job is done
      - name: Notify n8n Completion
        if: always()
        run: |
          if [ -n "${{ inputs.resumeUrl }}" ]; then
            curl -X POST "${{ inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d '{
              "status": "${{ job.status }}",
              "apk_url": "${{ steps.upload_file.outputs.apk_url }}",
              "app_name": "${{ inputs.app_name }}"
            }'
          fi
